version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - file-service

  auth-service:
    build:
      context: .
      dockerfile: auth_service/app/Dockerfile
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/auth_db
      SECRET_KEY: ttest111
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
    depends_on:
      - db
      - rabbitmq

  file-service:
    build:
      context: .
      dockerfile: file_service/app/Dockerfile
    ports:
      - "8002:8000"
    environment:
      SECRET_KEY: ttest111
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
    depends_on:
      - auth-service
      - rabbitmq

  notification-service:
    build:
      context: .
      dockerfile: notification_service/app/Dockerfile
    ports:
      - "8003:8000"
    environment:
      SECRET_KEY: ttest111
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
    depends_on:
      - auth-service
      - rabbitmq

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

volumes:
  postgres_data:
